### ISSUE TITLE
More information on the general purpose / use case / technologies related to this project

### ISSUE THREAD

**Issue by dberardo-com** [online-ml/beaver#1]
I am a newcomer in RiverML and i am trying to setup myself a robust production system for online learning at scale, specifically for unsupervised learning / anomalies detection.

I have got routed to this github project by this talk https://www.youtube.com/watch?v=nzFTmJnIakk and i have to say, i would like to know a bit more about the implementation strategy / roadmap / etc. of this project, and possibly how that reltes to riverML. 

Given the stage at which I am with the implementation of a production system using RiverML i feel like i could contribute to this project, but of course i would like to understand more the design choices behind it, and the general motivation.

I think that providing some links in the README could be already a good start, maybe a link to the talk itself, but also to your blog articles @MaxHalford , perhaps i could get start there.

Merci,

**Comment by MaxHalford** [comment]
Hello! Thanks for your interest and your relevant comments. I'm actually on holiday right now, but will significantly improve Beaver when I get back (in 10 days) :)

**Comment by MaxHalford** [comment]
@dberardo-com I just added some info to the README :)

**Comment by dberardo-com** [comment]
Great i will wait for more and figure out when all questions have been answered! 

In the meantime: what is the relation between this project and https://github.com/online-ml/chantilly ? Is the second one to be considered out-dated when beaver reaches production level or are those 2 intended to fullfil different needs and thus make sense to use them in parallel?

P.S. small typo in here: https://github.com/online-ml/beaver/tree/main/examples/taxis#steps (developping --> developing)

**Comment by MaxHalford** [comment]
Chantilly will be deprecated and Beaver will replace. In fact I'm going to freeze the Chantilly codebase and put a note linking to this project.

> P.S. small typo in here: https://github.com/online-ml/beaver/tree/main/examples/taxis#steps (developping --> developing)

Cheers!
