### ISSUE TITLE
Docker vulnerabilities

### ISSUE THREAD

**Issue by AndreaPra** [online-ml/beaver#16]
Hi,

I would like to tell you that I noticed that there are some vulnerabilities on the docker images that you use.

**Comment by MaxHalford** [comment]
Hey there. Can you list them here? Or tell me if there's a command I can run to see them for myself?

**Comment by AndreaPra** [comment]
I woudn't know how to list them. I could add some screenshots to explain what I mean.

<img width="1173" alt="Screenshot 2023-04-06 alle 16 00 13" src="https://user-images.githubusercontent.com/62189267/230400967-85a8e78e-8b86-4605-88cf-f9324b452e40.png">
<img width="1156" alt="Screenshot 2023-04-06 alle 16 00 50" src="https://user-images.githubusercontent.com/62189267/230400974-17088bf7-05ec-4ce3-8fb4-4ce0da0aaf03.png">
